<?php

/**
 * @file
 * Context Block Class
 */

/**
 * Implements hook_context_plugins().
 */
function context_block_class_context_plugins() {

  $plugins = array();
  $plugins['context_block_class_reaction_block'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'context_block_class') . '/plugins',
      'file' => 'context_block_class_reaction_block.inc',
      'class' => 'context_block_class_reaction_block',
      'parent' => 'context_reaction_block',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry_alter().
 */
function context_block_class_context_registry_alter(&$registry) {
  if (!empty($registry['reactions']['block'])) {
    $registry['reactions']['block']['plugin'] = 'context_block_class_reaction_block';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function context_block_class_theme_registry_alter(&$registry) {

  unset($registry['context_block_regions_form']['path']);
  unset($registry['context_block_regions_form']['file']);
  unset($registry['context_block_regions_form']['includes']);

  $registry['context_block_regions_form']['theme path'] = drupal_get_path('module', 'context_block_class');
  $registry['context_block_regions_form']['function'] = 'context_block_class_context_block_regions_form';
}

/**
 * Generates the AJAX enabled block administration portion of the context_ui admin form.
 * replaces 'theme_context_block_regions_form'
 * @see context/theme/context_reaction_block.theme.inc
 */
function context_block_class_context_block_regions_form($vars) {

  $form = $vars['form'];

  // Add draggable weights
  drupal_add_js('misc/tableheader.js');
  drupal_add_js(drupal_get_path('module', 'context') . '/plugins/context_reaction_block.js');
  drupal_add_css(drupal_get_path('module', 'context') . '/plugins/context_reaction_block.css');

  $output = '';

  foreach (element_children($form) as $region) {
    $attr = array(
      'id' => "context-blockform-region-{$region}",
      'class' => array("context-blockform-region"),
    );
    drupal_add_tabledrag($attr['id'], 'order', 'sibling', 'tabledrag-hide', NULL, NULL, FALSE);
    $rows = array();
    foreach (element_children($form[$region]) as $id) {
      $form[$region][$id]['weight']['#attributes'] = array('class' => array('tabledrag-hide'));
      $label = $form[$region][$id]['#value'];
      $remove = l(t('X'), $_GET['q'], array('fragment' => 'remove', 'attributes' => array('class' => array('remove'))));
      $rows[] = array(
        'data' => array($label, drupal_render($form[$region][$id]['weight']), drupal_render($form[$region][$id]['classes']), $remove),
        'class' => array('draggable'),
        'id' => $id,
      );
    }
    $output .= "<div class='label context-blockform-regionlabel-{$region}'>";
    $output .= l(t('+') . ' ' . t('Add'), $_GET['q'], array('fragment' => $region, 'attributes' => array('class' => array('add-block'))));
    $output .= $form[$region]['#title'];
    $output .= "</div>";
    $output .= theme('table', array('rows' => $rows, 'attributes' => $attr));
  }
  return $output;
}


function context_block_class_preprocess_block(&$vars) {

  if (!empty($vars['block']->classes)) {
    $context_classes = preg_split("/[\s,]+/", $vars['block']->classes);

    $vars['context_classes'] = $context_classes;
    $vars['classes_array'] = array_merge($vars['classes_array'], $context_classes);
  }

}